# Schimba PROJECT_NAME cu numele proiectului
WorldProject:  
        # Schimba APP_NAME1 cu numele aplicatiei
        PopulationApp:

            - view_name: all_countries
              url_path_name: all
              template_name: all_countries
            - view_name: choose_countries
              url_path_name: choose
              template_name: choose_countries



        # Schimba APP_NAME2 cu numele aplicatiei
        # APP_NAME2:
        #     - view_name: NUME_VIEW3
        #       url_path_name: NUME_URL3
        #       template_name: NUME_TEMPLATE3

        # Mai adauga aplicatii si view-uri in acest fel